### ISSUE TITLE
Clean import is not renaming the .htaccess file and adding a basic one. 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#23]
Start up DesktopServer, confirm Clean import is activated
Import archive ( https://www.dropbox.com/s/vkus3guprwnjwqf/Archive%20when%20importing%20with%20clean-import-did-not-replace-the-htaccess-file.zip?dl=0)
Check the files after import. 
*I did notice there is a -sav-{date} backup but this was prior, could this prevent a new one?
![screen shot 2018-06-08 at 12 42 06 pm](https://user-images.githubusercontent.com/1041421/41178169-48272302-6b1b-11e8-8b0c-7fbe8d54ab36.jpg)

**Comment by davejesch** [comment]
@GreggFranklin Not sure what you mean by "this was prior" -- do you mean this was from a prior import? Don't all the files get removed during the import process? Either way, having an extra file with a -sav-{date} in it would not interfere with renaming the .htaccess to .htaccess-sav-{date} since the data value is different each time.

**Comment by GreggFranklin** [comment]
I can not seem to recreate the issue and the original test archive is gone. I am going to close this ticket and if it should happen again reopen a new one.
