### ISSUE TITLE
Importing of Duplicator Pro File does not rename wp-config file or find database on Mac

### ISSUE THREAD

**Issue by MarcBenzakein** [ServerPress/clean-import#34]
#### STEPS TO REPRODUCE: 
1. On a Mac, start DesktopServer and select Import
2. Select Duplicator Pro file to import
3. Start Import

#### RESULTS: 
Upon the scrubbing of database step, DesktopServer creates error stating that database cannot be found.

#### EXPECTED RESULT:
DesktopServer imports without issue.

Browser: N/A
Browser Version: N/A
Operating System: Mac High Sierra

Link to original duplicator pro file here: https://www.dropbox.com/s/h4uoqomewh1ybbv/20180905_learnhowtostartandonlineb_b4e56184e171cf381199_20180905163149_archive.zip?dl=0

Link to "fixed" file (moved and renamed database to database.sql and renamed wp-config file from Duplicator named .txt file: https://www.dropbox.com/s/xd6n1r7x40hrthu/extracted.zip?dl=0

This only happens on Mac. Same archive works fine on Windows machines.

**Comment by davejesch** [comment]
I think Gregg already reported this. They've been changing the name of the config file, and sometimes it's not present if the file exists further up the path that the doc directory. Our plan is to copy the wp-config-sample.php. But having additional archives to test with and verify these changes is helpful.

Related #33

**Comment by MarcBenzakein** [comment]
Cloned latest repo, started with a fresh install of DS 3.9.2, replaced clean-import with master from repo. Still experiencing same issue on Mac.

**Comment by davejesch** [comment]
I need to see the log file. Edit wp-config and set WP_DEBUG to TRUE, then remove/comment out the "return;" that is in clean-import/prepend.php on line 355. The log file will be in ds-plugins/~clean-import-log.txt. Run the import again and attach the log file here.

**Comment by MarcBenzakein** [comment]
[~clean-import-log.txt](https://github.com/ServerPress/clean-import/files/2385253/clean-import-log.txt)

**Comment by davejesch** [comment]
Mac platform was not getting a trailing slash on the temp directory. Added code to ensure that's in place.

**Comment by GreggFranklin** [comment]
Duplicator Pro now also appears to create an archive with the .daf extension. Bob from Snapcreek(The guys who bought Duplicator) sent us an email contains helpful info and links to code. However these links are no longer valid. I have contacted him for new links and will add them to this thread. Here is the email: 
Changes from Duplicator Archives of the Past

1) Slight change in zip: In Duplicator Pro and a yet-to-be-released version of Duplicator Lite, the wp-config.php file is no longer stored as wp-config.php within the zip, instead it has been renamed wp-config-arc.txt. We do this so our installer can safely overwrite an existing site (up until the very last stage of an install we need to know a wp-config.php that already exists in the directory was there from the previous site and not the archive itself.  As a final part of our installer, we remove the old wp-config.php and rename wp-config-arc.txt to wp-config.php    For your purposes, your logic could simply just look for that file, and if it exists rename it upon import.

Note: Since the current and older versions of Duplicator Lite store wp-config.php as wp-config.php within the archive so ideally both types would be handled for maximum compatibility

2) DupArchive Format:  Contents are identical to the zips. We had a lot of problems bundling up large sites using PHP's zip capability so we created our own format, called DupArchive.  From, a high level the format looks like:

[Archive Header]
[File Header 1]
[Glob Header 1.1]
...
[Glob Header 1.n]
[File Header 2]
[Glob Header 2.1]
...
[Glob Header 2.n]

Essentially the files within the archive are split up between globs, with all files and globs having headers and various information about those items.  You'll be able to see the full details by examining the source code of the extractor.

Files of Interest
I have shared the following items in a Google Drive folder (link)

1) Windows DA Extract-Source.zip
The attached code is fairly straightforward and should assist in your understanding of this format.  Feel free to reuse whatever bits you would like.  Note that this code has a bit of special logic in it to handle archives that may have become corrupt, you may not need or want that part. 

2) Windows DA-Extract-EXE.zip
A zip containing the Windows/.Net extractor executable and its dependencies

3) 20180614_dev_431849c883c5bb094486_20180614164705_archive.daf
WordPress site bundled in a DupArchive.  Note that you can extract all the files in the .daf using the above extractor then browse to 'installer-backup.php' to have our installer do the actual installation (or you can just check out the files in the dup-installer directory if you want to see PHP source that can handle a .daf)

--
To extract, just put the .daf in the same directory as the exe and run the exe.

Please let me know if you have any questions.

Bob

.daf archive
https://www.dropbox.com/s/0ktuf0ifc0dd930/Duplicator%20Pro%20Packages.zip?dl=0

**Comment by GreggFranklin** [comment]
Issue has been tested and resolved.
