### ISSUE TITLE
# defines that have a ? seperating them and are on a single line

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/clean-import#6]

**Comment by GreggFranklin** [comment]
This happens regardless of Clean Import. So this should probably be moved to DS3 or DS4 for resolution. This happens with Multisite.

![screen shot 2017-06-08 at 10 14 49 am](https://user-images.githubusercontent.com/1041421/26941503-86290196-4c33-11e7-91c4-10d8b69729db.jpg)

Attached is the wp-config.php file to review.
[wp-config.php.zip](https://github.com/ServerPress/clean-import/files/1061781/wp-config.php.zip)

**Comment by davejesch** [comment]
Added code to normalize the line endings. The 'odd' character was a x0D, while all other line endings were x0Dx0A. Normalizing the line endings should solve the problem. Need to do testing on Mac.

By the way, this is not specific to MultiSite. Looks like it's caused by inconsistent line endings (some with CRLF and some with LF) on Mac. If it can be reproduced with a MS archive, please provide that so I can test and ensure the fix I have resolves it.

**Comment by GreggFranklin** [comment]
Ran a test creating a new multisite using the Clean Import Plugin, the result was the same.

![screen shot 2017-06-13 at 12 47 00 pm](https://user-images.githubusercontent.com/1041421/27101428-8f2d2c8e-5036-11e7-8f65-845f87f5e23e.jpg)

**Comment by davejesch** [comment]
Appears to be happening when DS creates the wp-config with MultiSite settings, it writes some line endings as 0x0D and not 0x0D 0x0A. Issue seems to be in the Xojo code that modifies wp-config.php for MultiSite.

**Comment by davejesch** [comment]
fixed with changes that Steve made here https://github.com/ServerPress/DS4/issues/123

**Comment by GreggFranklin** [comment]
Tested, and now works correctly
